#!/bin/bash
# Install script for .bashrc settings

INSTALL_DIR="$HOME/.bash"
if [ -d $INSTALL_DIR ]; then
  echo "Looks like you have a $INSTALL_DIR directory installed.  Good job!"
  exit
fi;

git clone git://github.com/fmoo/jackbash.git $INSTALL_DIR

# Make sure we have all the submodules  (e.g. pathogen, etc)
pushd $INSTALL_DIR
git submodule update --init
popd

for x in $HOME/.bashrc $HOME/.profile $HOME/.bash_profile ; do
  if [ -e $x ]; then
    mv $x "$x"_backup
  fi;
  echo "source $INSTALL_DIR/bashrc" > $x
done

if [ ! -e $HOME/.gitconfig ]; then
  # Copy because you have to fill in your user name
  cp $INSTALL_DIR/config/.gitconfig $HOME/.gitconfig
fi;

if [ -e $HOME/.screenrc ]; then
  mv $HOME/.screenrc $HOME/.screenrc_backup
fi;
ln -s $INSTALL_DIR/config/.screenrc $HOME/.screenrc

if [ -e $HOME/.inputrc ]; then
  mv $HOME/.inputrc $HOME/.inputrc_backup
fi;
ln -s $INSTALL_DIR/config/.inputrc $HOME/.inputrc

if [ -e $HOME/.vimrc ]; then
  mv $HOME/.vimrc $HOME/.vimrc_backup
fi;
ln -s $INSTALL_DIR/config/.vimrc $HOME/.vimrc

if [ -e $HOME/.vim ]; then
  mv $HOME/.vim $HOME/.vim_backup
fi;
ln -s $INSTALL_DIR/config/.vim $HOME/.vim

if [ -e $HOME/.tmux.conf ]; then
  mv $HOME/.tmux.conf $HOME/.tmux.conf_backup
fi;
ln -s $INSTALL_DIR/config/.tmux.conf $HOME/.tmux.conf

# Install homebrew
if [ $(uname) == "Darwin" ]; then
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  brew tap caskroom/cask
  brew install tmux
  brew install ctags
fi
